### ISSUE TITLE
[Bug]: 1.18.2 version says it needs 1.16

### ISSUE THREAD

**Issue by Gbergz** [someaddons/LootIntegrations#1]
### Describe the bug you're experiencing

Hey,
The latest release for 1.18.2 : https://www.curseforge.com/minecraft/mc-mods/loot-integrations/files/3749962

Says it needs minecraft 1.16 when booting up.

### Reproducability

Download 1.18.2 verison
Start game.
Crash.
Game says it needs 1.16

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.2

### Modloader version

Forge

### Logs

https://gist.github.com/Gbergz/a8b3466e721aecf1d9d4f4e1894cf743

**Comment by someaddons** [comment]
thanks, seems I actually managed to upload an outdated version :D fixed in 1.4
