### ISSUE TITLE
[Bug]: lootintegrations-1.18.2-3.7 Crash On Launch

### ISSUE THREAD

**Issue by theshadowake** [someaddons/LootIntegrations#10]
### Describe the bug you're experiencing

lootintegrations-1.18.2-3.7.jar has dependancies marked for Minecraft 1.19 and therefore won't load on 1.18.2.

### Reproducability

Load Minecraft 1.18.2 (Forge) with lootintegrations-1.18.2-3.7.jar

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18

### Modloader version

Forge

### Logs

N/A

**Comment by someaddons** [comment]
fixed in 3.8
