### ISSUE TITLE
[Bug]: Occasional Empty Loot Chests

### ISSUE THREAD

**Issue by serioos** [someaddons/LootIntegrations#13]
### Describe the bug you're experiencing

While looting the structures made by mods, I sometimes come across empty chests that should have loot. Just now, I had it happen 3 times back to back while looting the mermorph underwater village. Looked in the latest logs and found the errors too. They're at the bottom. Here's the log:

[latest.log](https://github.com/user-attachments/files/16122278/latest.log)

Minecraft 1.20.1 Forge 47.3.1
lootintegrations-1.20.1-3.7.jar
perfectplushies-forge-1.20.1-1.10.1.jar

### Reproducability

It can happen in any chest that is looted. Happened more while looting the mermorph underwater village's chests.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

https://gist.github.com/serioos/14d7f67a8b5ef5be4fea0eaa234ce30d

**Comment by serioos** [comment]
After some more exploring, it seems like the underwater chests are the ones most affected. I got empty chests in a row while looting the vanilla drowned ruined villages too.

**Comment by someaddons** [comment]
ye thats an issue the "perfectplushies" mod is causing, not related to loot integreations. Report to https://www.curseforge.com/minecraft/mc-mods/perfect-plushies please
