### ISSUE TITLE
[Bug]: Loot Table integration not working

### ISSUE THREAD

**Issue by iRedemption** [someaddons/LootIntegrations#15]
### Describe the bug you're experiencing

I made a datapack according to the examples and the pictures on the mod page. Spawned a chest with the test loot table integration and the loot table is not integrating. Tested both 1.20.1 and 1.21 as well as on forge and fabric.
[datapack.zip](https://github.com/user-attachments/files/16447360/Loot.Integrations.zip)

Mods loaded:
![image](https://github.com/user-attachments/assets/781c42cc-7f36-456e-b911-196d9ebd387a)

### Reproducability

1. Create a datapack. 
2. Add the a vanilla loot table to be integrated with another vanilla loot table. 
3. Use this command to spawn a chest with the desired loot table `/setblock ~ ~1 ~ minecraft:chest{LootTable:"minecraft:chests/simple_dungeon"}`
4. See that only the original loot table is spawning

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Fabric

### Logs

https://gist.github.com/iRedemption/29ce0521589fa94a610d40fe066603f0

**Comment by someaddons** [comment]
@iRedemption actually your issue is that your datapack is wrong, windows creates a sub folder in the zip folder, while the top of any datapack needs be have the data/ folder and the pack.mcmeta file. Can avoid it by selecting the data folder + pack.mcmeta and sending them to a zip together
