### ISSUE TITLE
[Error]: Version tagged incorrectly on CurseForge (lootintegrations-fabric-1.18.2-3.8.jar)

### ISSUE THREAD

**Issue by BBoldt** [someaddons/LootIntegrations#16]
### Describe the bug you're experiencing

This file is tagged incorrectly on curseforge, it's the fabric version and since it is tagged as forge, the client will add it to forge packs.

https://www.curseforge.com/minecraft/mc-mods/loot-integrations/files/5372174

![](https://i.imgur.com/YG8fXx2.png)

### Reproducability

-

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18

### Modloader version

Forge

### Logs

*

**Comment by someaddons** [comment]
thanks for letting me know, fixed^^
