### ISSUE TITLE
Balm Incompatibility

### ISSUE THREAD

**Issue by Answordy** [someaddons/LootIntegrations#2]
When balm is installed this mod doesn't work.
Tested on 1.18.2 forge 40.1.0 then 40.1.19, latest loot integrations, latest balm.
Used Dungeons Enhanced and Yung for testing, for the loot I used quark but tried other mods too.

I didn't add nor create loot tables, only "used" the built-in ones, they worked without balm, _however while i'm here I also would like to report that most of the Dungeons Enhanced support loot tables are incorrect in the files, like dungeons_enhanced:castle_cellar instead dungeons_enhanced:chests/castle/cellar, or at least they didn't work for me that way so I needed to create a datapack with the correct path._

**Comment by CvoidWyvern** [comment]
Also getting this on my end, Balm 3.0.3, LI 1.4, forge 40.1.25, that's a pretty major mod to have breaking it, would expect most packs utilizing this mod to at least have Waystones or Default Options.

**Comment by someaddons** [comment]
fixed
