### ISSUE TITLE
[Bug]: [Fabric 1.20.1] Loot Integrations not integrating loot from custom loot table

### ISSUE THREAD

**Issue by a-lakeside-viewer** [someaddons/LootIntegrations#21]
### Describe the bug you're experiencing

Good day!
I created a custom loot table called chest_spells and wanted to integrate it into all vanilla chests (as well as some dungeon chests). However, after multiple attempts, I am still unable to make it spit out one spell book in the ancient city chest. I've tried other chests and the issue seems to follow. I have also increased the weights and rolls of the loot table to no avail. I used the latest version for Fabric 1.20.1 and also tried older version of the Loot Integrations mod in case it worked on previous versions but that also didn't work.  I was wondering if maybe there was a bug preventing me from integrating the loot table.

Here are the loot table and integration file, respectively:
- [chest_spells.json](https://github.com/user-attachments/files/18088794/chest_spells.json) (fair warning: it has nearly 65000 lines (which may be the issue but it works when I make a loot chest using it so I am really not sure))
-  [spell_book_injections.json](https://github.com/user-attachments/files/18088827/spell_book_injections.json)

I'll also include a screenshot of my modlist in case it might help
![image](https://github.com/user-attachments/assets/2ab6992b-2ff4-40b3-96d3-aa9cfab342b1)

If I can send anything else to help, I'll gladly upload it as well. This has been bugging me for a full day now and I really have no clue what's wrong.

### Reproducability

After putting in the integration file and loot table in the datapack, I loaded into the world and used /lootr chests oshanz_changes:chests/chest_spells to check if the spell loot table works. Then I used /lootr chests minecraft:chests/ancient_city to generate a chest with ancient city loot inside. Only ancient city loot was present. Then I used a repeating setblock command with the ancient city loot ID in the NBT section but only the ancient city loot was inside.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

https://gist.github.com/a-lakeside-viewer/54990c16d65475005decd3c7e2d073fc

**Comment by someaddons** [comment]
it does look fine, can you try with the loot integrations "debugOutput" config set to true and a vanilla chest instead?
`/give @s chest{BlockEntityTag:{LootTable:"minecraft:chests/ancient_city"}`

The debug config writes loot gen attempts to the latest.log

**Comment by a-lakeside-viewer** [comment]
Here are the logs as requested. I removed Lootr and then performed the command and saw no changes in the loot inside the chest.
Gist link: https://gist.github.com/a-lakeside-viewer/7acf8141900826732aa0e00ae71bbd4c

I opened a few chests and here are the results
![2024-12-11_18 29 16](https://github.com/user-attachments/assets/41dfb483-e898-447a-8fc9-f97a57995648)

**Comment by someaddons** [comment]
just seeing that you're quite outdated, try updating to 4.0 of the mod and if that doesnt work could you send me the modpack?

**Comment by a-lakeside-viewer** [comment]
Sure thing! I used the latest version of Loot Integrations then switched to an older one to compare and the results were the same, sadly. Here is the link to the files I'm using currently since I haven't published the modpack yet. 

https://drive.google.com/file/d/1CP5M4VPB__3PKBAqRZ8-3Vq9fLeeIrKt/view?usp=sharing

**Comment by someaddons** [comment]
👍 gonna take a look

**Comment by someaddons** [comment]
released a fix for fabric 1.20.1, seems it wasnt loading the loottables right. Should work with 4.1

**Comment by a-lakeside-viewer** [comment]
OMG it's working now, HAHAHA! I wasn't going crazy! Thank you so much for your patience! You're awesome! I can finally continue my work.

![2024-12-11_22 22 26](https://github.com/user-attachments/assets/c126344d-997c-4c3a-9d24-93cf78b4abbd)

Thanks again, dude! Big preesh!

**Comment by someaddons** [comment]
Thanks for the detailed bug report 😄  it seems 3.7M other users failed to noticed 😅
