### ISSUE TITLE
suggestion for mod.

### ISSUE THREAD

**Issue by boris2255** [someaddons/LootIntegrations#4]
it would be more useful to open a config file to be able to "block" ceirtain mods from being added in the lootpack, and an option to increase the chest limit.

**Comment by boris2255** [comment]
the problem is that sometimes some mods items begin to clutter with other mods so it would be a lot better to be able to just decide what mods you dont want loot spawning in random chests

**Comment by someaddons** [comment]
for that I'd say make a datapack which adjsut that mod's loottable, and this mod already has an option to limit the maximum items put into chests
