### ISSUE TITLE
[Bug]: Barrels may still have normal loots

### ISSUE THREAD

**Issue by MelHeine** [someaddons/LootIntegrations#5]
### Describe the bug you're experiencing

I've noticed that barrols don't have they loot changed. Maybe I'm wrong, but it does not hurt to check it.

### Reproducability

Most barrels in Structory's structures.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

https://gist.github.com/I_have_no_idea_what_to_put_in_here

**Comment by someaddons** [comment]
this mod does not have any inherent compatibility for structory, for better loot you would need to add your own datapack to it
