### ISSUE TITLE
[Bug]: Integrated loot table refuses to integrate

### ISSUE THREAD

**Issue by gregest** [someaddons/LootIntegrations#6]
### Describe the bug you're experiencing

Trying to integrate pieces of equipment to a lot of various loot tables, however it doesn't seem to work, I even tried to integrate it into just a vanilla loot table and it doesn't seem to want to work. In the stuff.zip is where the loot table is and integrations has the integration.   

I originally had them together but I thought separating it might fix the issue, it didn't. 

I'm also using paxi which is a global datapack loader that automatically loads datapacks, but installing the datapack normally doesn't seem to fix it either.

[integrations.zip](https://github.com/someaddons/LootIntegrations/files/10944046/integrations.zip)
[stuff.zip](https://github.com/someaddons/LootIntegrations/files/10944047/stuff.zip)

### Reproducability

Write the datapack to integrate loot into loot tables    
Open game   
See that it didn't integrate 

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

https://gist.github.com/gregest/557fadd444664119bcfdb4c3138576cf

**Comment by someaddons** [comment]
found some problem with the fabric version, which the new 3.0 version should fix. Tested your datapack on it and it did work, so your datapack is fine aswell. Try 3.0 and see if its fixed for you.

Tip for testing:` /setblock ~ ~1 ~ minecraft:chest{LootTable:"betterdungeons:skeleton_dungeon/chests/common"}`

**Comment by gregest** [comment]
Well, it still doesn't seem to want to work for me even though I updated, it also just doesn't want to show up in Roughly Enough Loot Tables, and just as safety I set the rate for the item extremely high and it still didn't show up.   

I now also tried to change the alphabetical order of the datapacks so the integration loads after, change the load order in paxi so integration loads after, tried a different global datapack loader, tried putting the datapacks inside whatever temp folder opens (that obviously didn't work and good thing I had a backup), delete the erroring crafttweaker scripts in case and nothing worked. I will try to make a new profile with just this mod and mcda and paxi and see if that works 

[latest.log](https://github.com/someaddons/LootIntegrations/files/10948895/latest.log)

**Comment by someaddons** [comment]
it won't ever show up in Roughly Enough Loot Tables, as it adds bonus items upon chest generation and does not modify the original table itself

**Comment by gregest** [comment]
I guess it must be insanely rare then or I have no idea, I set the minimum rolls to a 1000 and set the weight of the item to a 100 and after going through a LOT of chests with a repeating commandblock, I still have not managed to find one

**Comment by someaddons** [comment]
with the setup you linked at the top(very first chest I summoned via ` /setblock ~ ~1 ~ minecraft:chest{LootTable:"betterdungeons:skeleton_dungeon/chests/common"}`:
![image](https://user-images.githubusercontent.com/38401808/224554925-0e6112f9-ab5d-4283-b8d9-4aeebc69ed3b.png)

Using your datapacks, put them into a worlds datapack folder(vanilla datapack)m and using these mods:

![image](https://user-images.githubusercontent.com/38401808/224555028-5621b6c8-a82d-4c1d-ba3f-8d1078f4e65c.png)

Btw global datapacks mod is better than paxi, paxi has some loading order issues

**Comment by gregest** [comment]
I really don't understand what's wrong for me then, since then I added more items to the table in case and it still doesn't work, nothing from the table shows up

https://user-images.githubusercontent.com/56032903/224557196-90c80a70-2a7e-4f74-b530-35f62c2ac283.mp4   

okay I feel kinda silly now because I just realized that mcda has its own loot table config that I didn't notice even though I looked in the configs a thousand time, that might be why it's acting weird

**Comment by someaddons** [comment]
which command are you using for testing?

**Comment by gregest** [comment]
the one you told me to try with, I just put it into a repeating command block so I can open them very fast

**Comment by someaddons** [comment]
hm quite odd, could you send me your whole instance(mods/configs/datapacks)? I suspect some mod incompat

**Comment by gregest** [comment]
I uploaded it to mega because github doesn't allow 400MB files, ignore the instance name as I was kinda upset at curseforge when I named it   

https://mega.nz/file/ZioiCQKT#bD-2qISTQU3W_-kfrLT6d29XdR_3H0CwTj0oX1c_9M0

**Comment by someaddons** [comment]
found the issue: balm mod does some incomatible modification which cancels the loot call for loot integrations, fixed it in v3.1

**Comment by gregest** [comment]
oh my god, thank you so much. I have no idea how you managed to figure that out but it seems to work perfectly now, I find at least 1 armor in every piece of chest     

thank you a billion times and for being so patient

**Comment by someaddons** [comment]
thanks aswell for taking the time and following through with this :) some hidden bugs like these take patience to track down.
Found & fixed finally working, yay!
