### ISSUE TITLE
[Bug]: Massive log spam with Loot Integrations 3.0+ and Minekea

### ISSUE THREAD

**Issue by SplendidAlakey** [someaddons/LootIntegrations#7]
### Describe the bug you're experiencing

**MC** 1.19.2
**Fabric** API 0.75.1 + Loader 0.14.17

When Loot Integrations 3.0+ is installed together with [Minekea](https://www.curseforge.com/minecraft/mc-mods/minekea-fabric), the logs get spammed a lot.

The last version, that is available for 1.19.2 and doesn't cause the issue, is 1.7: https://www.curseforge.com/minecraft/mc-mods/loot-integrations/files/3913352.

I checked my config to make sure I don't have any debugging logs enabled:

```
{
  "showcontainerloottable": {
    "desc:": "Set to true to print containers loottable on first open: default:false",
    "showcontainerloottable": false
  },
  "debugOutput": {
    "desc:": "Prints the added loot to the log if enabled: default:false",
    "debugOutput": false
  }
}
```

### Reproducability

1. Install [Minekea](https://www.curseforge.com/minecraft/mc-mods/minekea-fabric) and Loot Integrations 3.0+
2. Launch the game and load any world
3. Check your latest.log

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

https://gist.github.com/SplendidAlakey/ce6c02d557a2a67c41f90d250b32ef98

**Comment by someaddons** [comment]
Pretty sure this is on minekea's end, I guess them trying to change Identifiers in initialization here: https://github.com/chimericdream/minekea-fabric/blob/main/src/main/java/com/chimericdream/minekea/mixin/IdentifierMixin.java

went wrong somewhere. Please open a bug report there aswell
