### ISSUE TITLE
[Question]: Archeology Loot Integration?

### ISSUE THREAD

**Issue by generikb** [someaddons/LootIntegrations#8]
### Describe the bug you're experiencing

Yo!

I'm using Loot Integrations in my upcoming 1.20.1 modpack, and it's been really handy so far!

I want to add some loot tables to the new Archeology blocks (suspicious sand, gravel, etc)

Is that currently possible with Loot Integrations? If so, could you provide an example of what it would look like?

Thanks!

### Reproducability

N/A

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

N/A

**Comment by someaddons** [comment]
ye you can add loot from any to any, you just need to find the ID's to use (or create a custom loottable via datapack to use.

e.g.
```
{
  "loot_table": "minecraft:chests/simple_dungeon",
  "max_result_itemcount": 13,
  "integrated_loot_tables": {
    "minecraft:blocks/decorated_pot": 6
  }
}
```

this would add dungeon loot into the decorated pot block loottable(breaking it)
