### ISSUE TITLE
[Bug]: Server Crash on 1.16.5

### ISSUE THREAD

**Issue by Hanyuu123** [someaddons/LootIntegrations#9]
### Describe the bug you're experiencing

Server crashes when loot tries to add its loottable into a minecart entity? (thats what I understood from the log anyways)

### Reproducability

Get in game and load some chunks

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16

### Modloader version

Forge

### Logs

https://gist.github.com/Deepfriedyag/0339daac7c37b96e0bcfe0d0fedd8a62

**Comment by someaddons** [comment]
fixed
